version: 0.0.{build}

pull_requests:
  do_not_increment_build_number: true

os: Visual Studio 2017

platform:
  - x86

branches:
  only:
    - master

environment:
  matrix:
    - flavor: msvc
      QTDIR: C:\Qt\5.12\msvc2017_64
      MAKE: "nmake /NOLOGO"

init:
  - if %flavor%==mingw set PATH=C:\Qt\Tools\mingw530_32\bin;%PATH%
  - set PATH=%QTDIR%\bin;%PATH%
  - set PEGASUS_HOME=C:\hello\world

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - git submodule update --init

build_script:
  - md build
  - cd build
  - qmake ..
  - "%MAKE%"
  - "%MAKE% check"
  - "%MAKE% install"

  - windeployqt
      --release
      --plugindir C:\pegasus-frontend\lib
      --qmldir ..
      --no-translations
      --no-opengl-sw
      C:\pegasus-frontend
  - md C:\pegasus-frontend\lib\qml
  - ps: Get-ChildItem C:\pegasus-frontend -Filter 'Qt*' -Directory |
      Move-Item -Destination C:\pegasus-frontend\lib\qml

  - copy ..\README.md C:\pegasus-frontend
  - copy ..\LICENSE.md C:\pegasus-frontend
  - git describe --always > tmp_out.txt
  - set /p SUFFIX=<tmp_out.txt
  - 7z a pegasus-fe_%SUFFIX%_win-%flavor%.zip C:\pegasus-frontend

artifacts:
  - path: build\pegasus-fe_*.zip
