contact_links:
  - name: ğŸ§ Discord Server
    url: https://discord.gg/KTtzP6y
    about: Would you like to chat with us? Feel free to join our Discord community!
  - name: ğŸ•¹ï¸ RetroPie forum thread
    url: https://retropie.org.uk/forum/topic/9598/announcing-pegasus-frontend
    about: Tinkering with Raspberries and other board computers? Take a look at this thread!
